services:
  redis:
    image: "bitnami/redis:latest"
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - DISABLE_COMMANDS=FLUSHDB,FLUSHALL,CONFIG
    ports:
      - "6379:6379"
      - "8001:8001"
    volumes:
      - ./redis-data:/bitnami/redis/data

  dev:
    image: "node:16"
    command: bash -c "cd /app && npm install -g @nestjs/cli && npm install && npm run start:dev"
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
    volumes:
      - "./server:/app"
    ports:
      - "3000:3000"
    depends_on:
      - redis